from fastapi import FastAPI, Request
import time

from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

origins = ["*"]

app.add_middleware(CORSMiddleware,allow_origins=origins,allow_credentials=True,allow_methods=["*"],allow_headers=["*"])


doc_number=1


#these docs are generated by AI. When user makes the first request, the fisrt doc will be sent and the the doc number will be increased. This is a mock response.
docs={
    1:"IPC 302 - Punishment for murder",
    2:"IPC 420 - Cheating and dishonestly inducing delivery of property",
    3:"IPC 279 - Rash driving or riding on a public way"
}



@app.post("/chat")
async def chat(request:Request):
    global doc_number
    data=await request.json()
    if doc_number>3:
        return({"message":"All docs summarized"})
    doc=docs[doc_number]
    doc_number+=1
    time.sleep(2) #added a two second delay to show the loading state in frontend
    return{"message":doc}
